# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json* pnpm-lock.yaml* ./
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Ensure script is executable
RUN chmod +x misonote-mcp-client.js

# Default command
CMD ["node", "misonote-mcp-client.js"]
